<?php
/** @var \Facebook\BusinessExtension\Block\Pixel\Search $block */
if ($block->getFacebookPixelID()) {
    $eventId = \Facebook\BusinessExtension\Helper\EventIdGenerator::guidv4();
    //$block->trackServerEvent($eventId); não funciona para varnish
?>
    <script>
        fbq('set', 'agent', '<?= $block->getFacebookAgentVersion() ?>', '<?= $block->getFacebookPixelID() ?>');
        fbq('track', 'Search', {
                source: "<?= $block->getSource() ?>",
                pluginVersion: "<?= $block->getPluginVersion() ?>",
                search_string: "<?= $block->getSearchQuery() ?>"
            }
            , {
                eventID: "<?= $eventId ?>"
            }
        );
    </script>

<?php } ?>
